name: Test Actions

on:
  issue_comment:
    types:
      - created

jobs:
  like-pizza:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'I like pizza'}}
    steps:
      - name: Like pizza
      - run: |
          curl --location --request POST 'https://drone.inhouse.dh-darkstores-live.net/api/repos/deliveryhero/nv_automations/builds?branch=Trigger_Drone_Test' \
          --header 'Authorization: Bearer ${{ secrets.REGRESSION_DRONE_TOKEN }}'
